# Generated by Django 3.2 on 2023-12-06 14:31

from django.db import migrations, models
import django.db.models.deletion

import titles.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '__first__'),
        ('categories', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, verbose_name='название')),
                ('year', models.IntegerField(validators=[titles.validators.validate_years], verbose_name='год')),
                ('description', models.TextField(blank=True, max_length=254, null=True, verbose_name='описание')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='categories.category', verbose_name='категория')),
                ('genre', models.ManyToManyField(related_name='titles', to='genres.Genre', verbose_name='жанр')),
            ],
            options={
                'verbose_name': 'Произведение',
                'verbose_name_plural': 'Произведения',
            },
        ),
    ]
